# Generated by Django 6.0.3 on 2026-03-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_m2m_performers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproduct',
            name='performers',
        ),
        migrations.RemoveField(
            model_name='researchtask',
            name='funding',
        ),
        migrations.AddField(
            model_name='researchtask',
            name='executor_address',
            field=models.TextField(blank=True, help_text='Индекс, почтовый адрес, телефон/факс', verbose_name='Адрес исполнителя'),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='foundation',
            field=models.TextField(blank=True, verbose_name='Основание для проведения работы'),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='funding_source',
            field=models.CharField(blank=True, max_length=300, verbose_name='Источник финансирования'),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='goals',
            field=models.TextField(blank=True, verbose_name='Цели работы'),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='government_work_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Наименование государственной работы'),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место проведения работы'),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='tasks',
            field=models.TextField(blank=True, verbose_name='Задачи работы'),
        ),
        migrations.AlterField(
            model_name='researchtask',
            name='tz_number',
            field=models.CharField(blank=True, help_text='Шифр: "Депозит 2025"', max_length=100, verbose_name='Шифр'),
        ),
        migrations.CreateModel(
            name='ResearchTaskFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма (руб.)')),
                ('research_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_years', to='tasks.researchtask', verbose_name='НИР')),
            ],
            options={
                'verbose_name': 'Финансирование по году',
                'verbose_name_plural': 'Финансирование по годам',
                'ordering': ['year'],
                'unique_together': {('research_task', 'year')},
            },
        ),
    ]
