# Generated by Django 6.0.3 on 2026-03-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_researchproduct_performers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproduct',
            name='subtask',
        ),
    ]
