# Generated by Django 6.0.3 on 2026-03-25 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название должности')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория (ПКГ)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='ResearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование ТЗ')),
                ('tz_number', models.CharField(blank=True, max_length=100, verbose_name='Номер ТЗ')),
                ('customer', models.CharField(blank=True, max_length=500, verbose_name='Госзаказчик')),
                ('executor', models.CharField(blank=True, max_length=500, verbose_name='Исполнитель')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Финансирование')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'НИР',
                'verbose_name_plural': 'НИР',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень вложенности')),
                ('full_path', models.CharField(blank=True, max_length=500, verbose_name='Полный путь')),
                ('type', models.CharField(choices=[('directorate', 'Дирекция'), ('department', 'Отдел'), ('laboratory', 'Лаборатория'), ('group', 'Группа'), ('service', 'Служба'), ('division', 'Отделение')], default='department', max_length=20, verbose_name='Тип')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.department', verbose_name='Вышестоящее подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('department', models.CharField(choices=[('development', 'Разработка'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('sales', 'Продажи'), ('hr', 'HR'), ('administration', 'Администрация'), ('research', 'Исследования'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Отдел')),
                ('laboratory', models.CharField(blank=True, choices=[('lab1', 'Лаборатория №1'), ('lab2', 'Лаборатория №2'), ('lab3', 'Лаборатория №3'), ('research_lab', 'Исследовательская лаборатория'), ('test_lab', 'Тестовая лаборатория'), ('other', 'Другая')], max_length=50, null=True, verbose_name='Лаборатория')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сотрудник')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование продукции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('product_type', models.CharField(choices=[('report', 'Отчет'), ('article', 'Статья'), ('patent', 'Патент'), ('methodology', 'Методика'), ('software', 'Программное обеспечение'), ('other', 'Другое')], default='report', max_length=50, verbose_name='Тип продукции')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Планируемая дата начала')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Планируемая дата окончания')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Фактическая дата начала')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('delayed', 'Задержка'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('completion_percent', models.IntegerField(default=0, verbose_name='Процент выполнения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_products', to='tasks.employee', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Научная продукция',
                'verbose_name_plural': 'Научная продукция',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('responsible', 'Ответственный исполнитель'), ('executor', 'Исполнитель'), ('consultant', 'Консультант'), ('reviewer', 'Рецензент'), ('approver', 'Утверждающий')], default='executor', max_length=20, verbose_name='Роль')),
                ('contribution_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма долей всех исполнителей может быть больше 100%', max_digits=5, null=True, verbose_name='Доля участия (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_performers', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performers', to='tasks.employee', verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performers', to='tasks.researchproduct', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Исполнитель продукции',
                'verbose_name_plural': 'Исполнители продукции',
                'ordering': ['-role', 'employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(verbose_name='Номер этапа')),
                ('title', models.TextField(verbose_name='Наименование этапа')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('performers', models.ManyToManyField(blank=True, related_name='research_stages', to='tasks.employee', verbose_name='Исполнители')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_stages', to='tasks.employee', verbose_name='Ответственный')),
                ('research_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tasks.researchtask', verbose_name='НИР')),
            ],
            options={
                'verbose_name': 'Этап НИР',
                'verbose_name_plural': 'Этапы НИР',
                'ordering': ['stage_number'],
            },
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='research_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tasks.researchstage', verbose_name='Этап НИР'),
        ),
        migrations.CreateModel(
            name='ResearchSubstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substage_number', models.CharField(max_length=10, verbose_name='Номер подэтапа')),
                ('title', models.TextField(verbose_name='Наименование подэтапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('performers', models.ManyToManyField(blank=True, related_name='research_substages', to='tasks.employee', verbose_name='Исполнители')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_substages', to='tasks.employee', verbose_name='Ответственный')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substages', to='tasks.researchstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Подэтап НИР',
                'verbose_name_plural': 'Подэтапы НИР',
                'ordering': ['substage_number'],
            },
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='research_substage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tasks.researchsubstage', verbose_name='Подэтап НИР'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='research_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tasks.researchtask', verbose_name='НИР'),
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.DecimalField(decimal_places=2, default=1.0, help_text='Например: 1.0, 0.5, 0.25', max_digits=3, verbose_name='Ставка')),
                ('employment_type', models.CharField(choices=[('main', 'Основное'), ('internal_combination', 'Внутреннее совместительство'), ('external_combination', 'Внешнее совместительство'), ('combination', 'Совмещение'), ('part_time', 'Частичная занятость'), ('vacant', 'Вакансия'), ('decree', 'Декретный отпуск'), ('allowance', 'Надбавка')], default='main', max_length=30, verbose_name='Тип занятости')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='tasks.department', verbose_name='Подразделение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='tasks.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='tasks.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Штатная единица',
                'verbose_name_plural': 'Штатные единицы',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.CharField(max_length=10, verbose_name='Номер этапа')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Выход/Результат')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое начало')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое окончание')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('delayed', 'Задержка')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('performers', models.ManyToManyField(blank=True, related_name='subtasks', to='tasks.employee', verbose_name='Исполнители')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_subtasks', to='tasks.employee', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'ordering': ['stage_number'],
            },
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tasks.subtask', verbose_name='Подэтап'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='todo', max_length=20, verbose_name='Статус')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.employee', verbose_name='Исполнители')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Основная задача'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='dept_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['type'], name='dept_type_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='dept_name_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['full_path'], name='dept_full_path_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['level'], name='dept_level_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='emp_name_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='emp_email_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='emp_active_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='emp_dept_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productperformer',
            unique_together={('product', 'employee')},
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['department'], name='staff_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['employee'], name='staff_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['position'], name='staff_position_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['is_active'], name='staff_active_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['employment_type'], name='staff_empl_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffposition',
            unique_together={('employee', 'department', 'position', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='task_user_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_date'], name='task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task'], name='subtask_task_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['status'], name='subtask_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['priority'], name='subtask_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['planned_end'], name='subtask_planned_end_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('task', 'stage_number')},
        ),
    ]
