# Generated by Django 5.0.3 on 2026-03-17 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование ТЗ')),
                ('tz_number', models.CharField(blank=True, max_length=100, verbose_name='Номер ТЗ')),
                ('customer', models.CharField(blank=True, max_length=500, verbose_name='Госзаказчик')),
                ('executor', models.CharField(blank=True, max_length=500, verbose_name='Исполнитель')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Финансирование')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'НИР',
                'verbose_name_plural': 'НИР',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('department', models.CharField(choices=[('development', 'Разработка'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('sales', 'Продажи'), ('hr', 'HR'), ('administration', 'Администрация'), ('research', 'Исследования'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Отдел')),
                ('laboratory', models.CharField(blank=True, choices=[('lab1', 'Лаборатория №1'), ('lab2', 'Лаборатория №2'), ('lab3', 'Лаборатория №3'), ('research_lab', 'Исследовательская лаборатория'), ('test_lab', 'Тестовая лаборатория'), ('other', 'Другая')], max_length=50, null=True, verbose_name='Лаборатория')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сотрудник')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(verbose_name='Номер этапа')),
                ('title', models.TextField(verbose_name='Наименование этапа')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('performers', models.ManyToManyField(blank=True, related_name='research_stages', to='tasks.employee', verbose_name='Исполнители')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_stages', to='tasks.employee', verbose_name='Ответственный')),
                ('research_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tasks.researchtask', verbose_name='НИР')),
            ],
            options={
                'verbose_name': 'Этап НИР',
                'verbose_name_plural': 'Этапы НИР',
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSubstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substage_number', models.CharField(max_length=10, verbose_name='Номер подэтапа')),
                ('title', models.TextField(verbose_name='Наименование подэтапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('performers', models.ManyToManyField(blank=True, related_name='research_substages', to='tasks.employee', verbose_name='Исполнители')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_substages', to='tasks.employee', verbose_name='Ответственный')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substages', to='tasks.researchstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Подэтап НИР',
                'verbose_name_plural': 'Подэтапы НИР',
                'ordering': ['substage_number'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование продукции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок представления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('delayed', 'Задержка')], default='pending', max_length=20, verbose_name='Статус')),
                ('performers', models.ManyToManyField(blank=True, related_name='research_products', to='tasks.employee', verbose_name='Исполнители')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_products', to='tasks.employee', verbose_name='Ответственный')),
                ('substage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tasks.researchsubstage', verbose_name='Подэтап')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='todo', max_length=20, verbose_name='Статус')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.employee', verbose_name='Исполнители')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField(verbose_name='Номер этапа')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Выход/Результат')),
                ('priority', models.CharField(choices=[('critical', '🔴 Критический'), ('high', '🟠 Высокий'), ('medium', '🟡 Средний'), ('low', '🟢 Низкий')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое начало')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое окончание')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('delayed', 'Задержка')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('performers', models.ManyToManyField(blank=True, related_name='subtasks', to='tasks.employee', verbose_name='Исполнители')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_subtasks', to='tasks.employee', verbose_name='Ответственный')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Основная задача')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'ordering': ['stage_number'],
                'unique_together': {('task', 'stage_number')},
            },
        ),
    ]
