# Generated by Django 6.0.3 on 2026-03-14 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('department', models.CharField(choices=[('development', 'Разработка'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('sales', 'Продажи'), ('hr', 'HR'), ('administration', 'Администрация'), ('research', 'Исследования'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Отдел')),
                ('laboratory', models.CharField(blank=True, choices=[('lab1', 'Лаборатория №1'), ('lab2', 'Лаборатория №2'), ('lab3', 'Лаборатория №3'), ('research_lab', 'Исследовательская лаборатория'), ('test_lab', 'Тестовая лаборатория'), ('other', 'Другая')], max_length=50, null=True, verbose_name='Лаборатория')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сотрудник')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.employee', verbose_name='Исполнители'),
        ),
    ]
