# Generated by Django 5.0.3 on 2026-03-23 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchproduct',
            options={'ordering': ['-created_date'], 'verbose_name': 'Научная продукция', 'verbose_name_plural': 'Научная продукция'},
        ),
        migrations.RemoveField(
            model_name='researchproduct',
            name='performers',
        ),
        migrations.RemoveField(
            model_name='researchproduct',
            name='substage',
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='actual_end',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='actual_start',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата начала'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='completion_percent',
            field=models.IntegerField(default=0, verbose_name='Процент выполнения'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='planned_end',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата окончания'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='planned_start',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата начала'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='product_type',
            field=models.CharField(choices=[('report', 'Отчет'), ('article', 'Статья'), ('patent', 'Патент'), ('methodology', 'Методика'), ('software', 'Программное обеспечение'), ('other', 'Другое')], default='report', max_length=50, verbose_name='Тип продукции'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='research_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tasks.researchstage', verbose_name='Этап НИР'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='research_substage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tasks.researchsubstage', verbose_name='Подэтап НИР'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='research_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tasks.researchtask', verbose_name='НИР'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tasks.subtask', verbose_name='Подэтап'),
        ),
        migrations.AddField(
            model_name='researchproduct',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='researchproduct',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='researchproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('delayed', 'Задержка'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ProductPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('responsible', 'Ответственный исполнитель'), ('executor', 'Исполнитель'), ('consultant', 'Консультант'), ('reviewer', 'Рецензент'), ('approver', 'Утверждающий')], default='executor', max_length=20, verbose_name='Роль')),
                ('contribution_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма долей всех исполнителей может быть больше 100%', max_digits=5, null=True, verbose_name='Доля участия (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_performers', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performers', to='tasks.employee', verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performers', to='tasks.researchproduct', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Исполнитель продукции',
                'verbose_name_plural': 'Исполнители продукции',
                'ordering': ['-role', 'employee__last_name'],
                'unique_together': {('product', 'employee')},
            },
        ),
    ]
