# Generated by Django 5.0.3 on 2026-03-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_subtask_priority_alter_subtask_stage_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название должности')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория (ПКГ)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень вложенности')),
                ('full_path', models.CharField(blank=True, max_length=500, verbose_name='Полный путь')),
                ('type', models.CharField(choices=[('directorate', 'Дирекция'), ('department', 'Отдел'), ('laboratory', 'Лаборатория'), ('group', 'Группа'), ('service', 'Служба'), ('division', 'Отделение')], default='department', max_length=20, verbose_name='Тип')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.department', verbose_name='Вышестоящее подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.DecimalField(decimal_places=2, default=1.0, help_text='Например: 1.0, 0.5, 0.25', max_digits=3, verbose_name='Ставка')),
                ('employment_type', models.CharField(choices=[('main', 'Основное'), ('internal_combination', 'Внутреннее совместительство'), ('external_combination', 'Внешнее совместительство'), ('combination', 'Совмещение'), ('part_time', 'Частичная занятость'), ('vacant', 'Вакансия'), ('decree', 'Декретный отпуск'), ('allowance', 'Надбавка')], default='main', max_length=30, verbose_name='Тип занятости')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='tasks.department', verbose_name='Подразделение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='tasks.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='tasks.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Штатная единица',
                'verbose_name_plural': 'Штатные единицы',
                'unique_together': {('employee', 'department', 'position', 'start_date')},
            },
        ),
    ]
