# Generated by Django 5.0.3 on 2026-03-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_position_department_staffposition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='tasks_depar_parent__3771dc_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['type'], name='tasks_depar_type_09914e_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='tasks_depar_name_1bc300_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['full_path'], name='tasks_depar_full_pa_cf48b2_idx'),
        ),
    ]
