# Generated by Django 5.0.3 on 2026-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_subtask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='priority',
            field=models.CharField(choices=[('critical', '🔴 Критический'), ('high', '🟠 Высокий'), ('medium', '🟡 Средний'), ('low', '🟢 Низкий')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
    ]
