# Generated by Django 5.0.3 on 2026-03-20 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_department_tasks_depar_parent__3771dc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='dept_parent_idx',
            old_name='tasks_depar_parent__3771dc_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='dept_type_idx',
            old_name='tasks_depar_type_09914e_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='dept_name_idx',
            old_name='tasks_depar_name_1bc300_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='dept_full_path_idx',
            old_name='tasks_depar_full_pa_cf48b2_idx',
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['level'], name='dept_level_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='emp_name_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='emp_email_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='emp_active_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='emp_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['department'], name='staff_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['employee'], name='staff_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['position'], name='staff_position_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['is_active'], name='staff_active_idx'),
        ),
        migrations.AddIndex(
            model_name='staffposition',
            index=models.Index(fields=['employment_type'], name='staff_empl_type_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task'], name='subtask_task_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['status'], name='subtask_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['priority'], name='subtask_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['planned_end'], name='subtask_planned_end_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='task_user_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_date'], name='task_created_idx'),
        ),
    ]
